const express = require('express');
const { createClient } = require('@supabase/supabase-js');
const cors = require('cors');
const path = require('path');
const axios = require('axios');
const fs = require('fs');
const dotenv = require('dotenv');
const cron = require('node-cron');
require('dotenv').config();
const { fileURLToPath } = require('url');
const sanitize = require('sanitize-html');
const bcrypt = require('bcrypt');
const rateLimit = require('express-rate-limit');
const Joi = require('joi');
const jwt = require('jsonwebtoken');
const cheerio = require('cheerio');
const bodyParser = require('body-parser');
const app = express();
const PORT = 8080;

